In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [2]:
# read log file baselines and ralis

In [3]:
# path to logs
path = '/mnt/qb/baumgartner/cschmidt77_data/FINAL_ACDC3232/'

In [4]:
exp_2_acdc_baselines = os.listdir(path)

In [5]:
exp_2_acdc_baselines = [exp for exp in exp_2_acdc_baselines]

In [6]:
exp_2_acdc_baselines

['2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_1184_seed_123',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_1184_seed_20',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_1184_seed_234',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_1184_seed_55',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_1184_seed_77',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_128_seed_123',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_128_seed_20',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_128_seed_234',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_128_seed_55',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_128_seed_77',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_1424_seed_123',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_1424_seed_20',
 '2021-11-03-acdc_ImageNetBackbone_baseline_random_3232_budget_1

In [7]:
data_frame_lists = []
for exp in exp_2_acdc_baselines: 
    exp_path = path + exp + '/Mean_3D_DSC.txt'
    if os.path.isfile(exp_path): 
        names = ["All classes", "background", "RV", "MYO", "LV", "Experiment", "seed", "budget"]
        data = pd.read_csv(exp_path, nrows=1, skiprows=1, names=names, sep ='\t')
        data["Experiment"] = exp
        data = data[["Experiment", "seed", "budget", "All classes", "background", "RV", "MYO", "LV"]]
        if 'ralis' in exp:
            data['al-algo'] = 'ralis'
        else:
            data['al-algo'] = exp.split('_')[3]
        data['budget'] = exp.split('_')[-3]    
        data['seed'] = exp.split('_')[-1]
        data_frame_lists.append(data)

frame = pd.concat(data_frame_lists, axis=0, ignore_index=True)

In [8]:
frame

Experiment seed budget  \
0    2021-11-03-acdc_ImageNetBackbone_baseline_rand...  123   1184   
1    2021-11-03-acdc_ImageNetBackbone_baseline_rand...   20   1184   
2    2021-11-03-acdc_ImageNetBackbone_baseline_rand...  234   1184   
3    2021-11-03-acdc_ImageNetBackbone_baseline_rand...   55   1184   
4    2021-11-03-acdc_ImageNetBackbone_baseline_rand...   77   1184   
..                                                 ...  ...    ...   
215  2021-11-19-acdc_ImageNetBackbone_baseline_rali...  123    960   
216  2021-11-19-acdc_ImageNetBackbone_baseline_rali...   20    960   
217  2021-11-19-acdc_ImageNetBackbone_baseline_rali...  234    960   
218  2021-11-19-acdc_ImageNetBackbone_baseline_rali...   55    960   
219  2021-11-19-acdc_ImageNetBackbone_baseline_rali...   77    960   

     All classes  background        RV       MYO        LV al-algo  
0       0.288909    0.981193  0.000000  0.000000  0.174445  random  
1       0.289900    0.979271  0.180330  0.000000  0.000000  random  
2       0.268684    0.980164  0.000274  0.000000  0.094297  random  
3       0.262789    0.979944  0.000000  0.014674  0.056537  random  
4       0.263073    0.980028  0.000000  0.000000  0.072266  random  
..           ...         ...       ...       ...       ...     ...  
215     0.754540    0.991934  0.568128  0.612408  0.845691   ralis  
216     0.709371    0.990661  0.523214  0.511460  0.812149   ralis  
217     0.459895    0.984898  0.379415  0.003832  0.471433   ralis  
218     0.259818    0.979893  0.000000  0.003668  0.055712   ralis  
219     0.790421    0.993799  0.676259  0.667024  0.824603   ralis  

[220 rows x 9 columns]

In [8]:
frame_6464

Experiment seed budget  \
0    2021-11-03-acdc_ImageNetBackbone_baseline_entr...  123   1184   
1    2021-11-03-acdc_ImageNetBackbone_baseline_entr...   20   1184   
2    2021-11-03-acdc_ImageNetBackbone_baseline_entr...  234   1184   
3    2021-11-03-acdc_ImageNetBackbone_baseline_entr...   55   1184   
4    2021-11-03-acdc_ImageNetBackbone_baseline_entr...   77   1184   
..                                                 ...  ...    ...   
175  2021-11-04-acdc_ralis_ImageNetBackbone_budget_...  123    960   
176  2021-11-04-acdc_ralis_ImageNetBackbone_budget_...   20    960   
177  2021-11-04-acdc_ralis_ImageNetBackbone_budget_...  234    960   
178  2021-11-04-acdc_ralis_ImageNetBackbone_budget_...   55    960   
179  2021-11-04-acdc_ralis_ImageNetBackbone_budget_...   77    960   

     All classes  background        RV       MYO        LV  al-algo  
0       0.854858    0.995097  0.826165  0.717412  0.880758  entropy  
1       0.857708    0.995153  0.818684  0.719738  0.897258  entropy  
2       0.862229    0.995396  0.814165  0.748470  0.890883  entropy  
3       0.843088    0.994722  0.784420  0.718682  0.874527  entropy  
4       0.880347    0.996098  0.830081  0.782838  0.912372  entropy  
..           ...         ...       ...       ...       ...      ...  
175     0.861899    0.995227  0.802851  0.745293  0.904225    ralis  
176     0.852645    0.995185  0.780094  0.736050  0.899253    ralis  
177     0.868417    0.995655  0.801995  0.765190  0.910827    ralis  
178     0.866886    0.995654  0.791263  0.772476  0.908152    ralis  
179     0.850508    0.994740  0.796227  0.728399  0.882666    ralis  

[180 rows x 9 columns]

In [9]:
frame_new = frame.drop(columns="Experiment")

In [10]:
pd.options.display.float_format = "{:,.3f}".format

In [11]:
frame_new.sort_values(by=['All classes'], ascending=False)

seed budget  All classes  background    RV   MYO    LV  al-algo
149   77   3568        0.909       0.998 0.867 0.850 0.920  entropy
146   20   3568        0.907       0.997 0.859 0.849 0.925  entropy
90   123   3568        0.907       0.997 0.845 0.858 0.929     bald
148   55   3568        0.906       0.997 0.854 0.850 0.922  entropy
91    20   3568        0.905       0.997 0.853 0.848 0.921     bald
..   ...    ...          ...         ...   ...   ...   ...      ...
183   55     16        0.245       0.980 0.000 0.000 0.000    ralis
15   123     16        0.245       0.980 0.000 0.000 0.000   random
195  123     32        0.245       0.980 0.000 0.000 0.000    ralis
197  234     32        0.245       0.980 0.000 0.000 0.000    ralis
73    55     16        0.245       0.980 0.000 0.000 0.000     bald

[220 rows x 8 columns]

In [12]:
frame_new['budget']

0      1184
1      1184
2      1184
3      1184
4      1184
       ... 
215     960
216     960
217     960
218     960
219     960
Name: budget, Length: 220, dtype: object

## BALD

In [13]:
for budget in frame_new['budget'].unique():
    # create data frames for different budgets names e.g. imgStd01_budget_128
    df_img_bald = frame_new.loc[(frame_new['al-algo'] == 'bald') & (frame_new['budget'] == budget)]
    globals()['img_bald_%s' % budget] = df_img_bald.groupby(['budget']).agg({'All classes': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'RV':['mean', 'std'], 'MYO':['mean', 'std'], 'LV':['mean', 'std']})

In [14]:
img_bald_128

All classes       background          RV         MYO          LV      
              mean   std       mean   std  mean   std  mean   std  mean   std
budget                                                                       
128          0.583 0.077      0.988 0.001 0.310 0.096 0.373 0.155 0.661 0.110

## Entropy

In [15]:
for budget in frame_new['budget'].unique():
    # create data frames for different budgets names e.g. imgStd01_budget_128
    df_img_entropy = frame_new.loc[(frame_new['al-algo'] == 'entropy') & (frame_new['budget'] == budget)]
    globals()['img_entropy_%s' % budget] = df_img_entropy.groupby(['budget']).agg({'All classes': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'RV':['mean', 'std'], 'MYO':['mean', 'std'], 'LV':['mean', 'std']})

In [16]:
img_entropy_128

All classes       background          RV         MYO          LV      
              mean   std       mean   std  mean   std  mean   std  mean   std
budget                                                                       
128          0.379 0.183      0.982 0.005 0.151 0.207 0.127 0.192 0.254 0.331

## Random

In [17]:
for budget in frame_new['budget'].unique():
    # create data frames for different budgets names e.g. imgStd01_budget_128
    df_img_random = frame_new.loc[(frame_new['al-algo'] == 'random') & (frame_new['budget'] == budget)]
    globals()['img_random_%s' % budget] = df_img_random.groupby(['budget']).agg({'All classes': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'RV':['mean', 'std'], 'MYO':['mean', 'std'], 'LV':['mean', 'std']})

In [18]:
img_random_128

All classes       background          RV         MYO          LV      
              mean   std       mean   std  mean   std  mean   std  mean   std
budget                                                                       
128          0.267 0.028      0.980 0.001 0.000 0.000 0.001 0.002 0.087 0.112

## RALIS

In [19]:
for budget in frame_new['budget'].unique():
    # create data frames for different budgets names e.g. imgStd01_budget_128
    df_img_ralis = frame_new.loc[(frame_new['al-algo'] == 'ralis') & (frame_new['budget'] == budget)]
    globals()['img_ralis_%s' % budget] = df_img_ralis.groupby(['budget']).agg({'All classes': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'RV':['mean', 'std'], 'MYO':['mean', 'std'], 'LV':['mean', 'std']})

In [20]:
img_ralis_128

All classes       background          RV         MYO          LV      
              mean   std       mean   std  mean   std  mean   std  mean   std
budget                                                                       
128          0.378 0.114      0.982 0.003 0.077 0.124 0.119 0.123 0.336 0.277

## Concatenated for al-algorithms

In [21]:
# budgets 64 128 592 960 1184 1424 1904 2384 3568

In [22]:
budgets = frame_new['budget'].unique()

In [23]:
budgets

array(['1184', '128', '1424', '16', '1904', '2384', '32', '3568', '592',
       '64', '960'], dtype=object)

## Random

In [24]:
df_img_random = pd.concat([img_random_64, img_random_128, img_random_592,
                           img_random_960, img_random_1184, img_random_1424,
                           img_random_1904, img_random_2384, img_random_3568])

In [25]:
df_img_random

All classes       background          RV         MYO          LV      
              mean   std       mean   std  mean   std  mean   std  mean   std
budget                                                                       
64           0.272 0.022      0.980 0.000 0.033 0.056 0.000 0.000 0.074 0.102
128          0.267 0.028      0.980 0.001 0.000 0.000 0.001 0.002 0.087 0.112
592          0.265 0.013      0.980 0.000 0.001 0.001 0.001 0.002 0.079 0.051
960          0.262 0.015      0.980 0.001 0.034 0.073 0.000 0.000 0.034 0.028
1184         0.275 0.014      0.980 0.001 0.036 0.081 0.003 0.007 0.080 0.064
1424         0.274 0.020      0.981 0.001 0.007 0.010 0.002 0.003 0.105 0.073
1904         0.313 0.024      0.982 0.001 0.000 0.000 0.002 0.003 0.268 0.098
2384         0.317 0.042      0.981 0.001 0.034 0.060 0.053 0.053 0.201 0.069
3568         0.368 0.036      0.982 0.001 0.146 0.197 0.091 0.060 0.254 0.186

## Entropy

In [26]:
df_img_entropy = pd.concat([img_entropy_64, img_entropy_128, img_entropy_592,
                           img_entropy_960, img_entropy_1184, img_entropy_1424,
                           img_entropy_1904, img_entropy_2384, img_entropy_3568])

In [27]:
df_img_entropy

All classes       background          RV         MYO          LV      
              mean   std       mean   std  mean   std  mean   std  mean   std
budget                                                                       
64           0.339 0.176      0.982 0.004 0.114 0.227 0.086 0.192 0.176 0.291
128          0.379 0.183      0.982 0.005 0.151 0.207 0.127 0.192 0.254 0.331
592          0.676 0.223      0.990 0.006 0.476 0.270 0.532 0.274 0.704 0.345
960          0.690 0.251      0.990 0.006 0.546 0.310 0.548 0.310 0.676 0.379
1184         0.722 0.156      0.991 0.004 0.588 0.206 0.557 0.222 0.753 0.198
1424         0.726 0.228      0.991 0.007 0.578 0.307 0.585 0.312 0.750 0.290
1904         0.700 0.275      0.991 0.007 0.565 0.349 0.556 0.360 0.688 0.395
2384         0.807 0.097      0.994 0.003 0.657 0.151 0.703 0.183 0.876 0.066
3568         0.789 0.230      0.995 0.006 0.696 0.313 0.675 0.333 0.792 0.268

## BALD

In [28]:
df_img_bald = pd.concat([img_bald_64, img_bald_128, img_bald_592,
                           img_bald_960, img_bald_1184, img_bald_1424,
                           img_bald_1904, img_bald_2384, img_bald_3568])

In [29]:
df_img_bald

All classes       background          RV         MYO          LV      
              mean   std       mean   std  mean   std  mean   std  mean   std
budget                                                                       
64           0.456 0.070      0.985 0.001 0.175 0.188 0.204 0.099 0.458 0.086
128          0.583 0.077      0.988 0.001 0.310 0.096 0.373 0.155 0.661 0.110
592          0.780 0.026      0.993 0.001 0.637 0.105 0.643 0.048 0.847 0.034
960          0.824 0.014      0.995 0.001 0.698 0.063 0.725 0.020 0.877 0.013
1184         0.822 0.016      0.994 0.000 0.711 0.063 0.715 0.038 0.869 0.025
1424         0.839 0.020      0.995 0.001 0.726 0.047 0.753 0.029 0.880 0.029
1904         0.861 0.016      0.996 0.001 0.754 0.032 0.791 0.028 0.904 0.017
2384         0.883 0.009      0.996 0.000 0.802 0.026 0.820 0.010 0.912 0.006
3568         0.902 0.005      0.997 0.000 0.842 0.010 0.847 0.007 0.923 0.005

## RALIS

In [30]:
df_img_ralis = pd.concat([img_ralis_64, img_ralis_128, img_ralis_592,
                           img_ralis_960, img_ralis_1184, img_ralis_1424,
                           img_ralis_1904, img_ralis_2384, img_ralis_3568])

In [31]:
df_img_ralis

All classes       background          RV         MYO          LV      
              mean   std       mean   std  mean   std  mean   std  mean   std
budget                                                                       
64           0.321 0.086      0.981 0.003 0.074 0.102 0.065 0.122 0.163 0.233
128          0.378 0.114      0.982 0.003 0.077 0.124 0.119 0.123 0.336 0.277
592          0.498 0.233      0.985 0.005 0.266 0.282 0.323 0.297 0.417 0.376
960          0.595 0.228      0.988 0.006 0.429 0.263 0.360 0.330 0.602 0.342
1184         0.571 0.295      0.986 0.010 0.367 0.338 0.419 0.373 0.511 0.466
1424         0.596 0.246      0.988 0.006 0.404 0.320 0.392 0.309 0.601 0.356
1904         0.651 0.241      0.990 0.006 0.469 0.290 0.487 0.343 0.658 0.340
2384         0.708 0.214      0.991 0.005 0.522 0.300 0.563 0.333 0.755 0.218
3568         0.746 0.246      0.992 0.007 0.612 0.346 0.621 0.350 0.758 0.281

## Concatenate all al-algos

In [32]:
df_img_al_algos = pd.concat([df_img_ralis, df_img_entropy, df_img_bald, df_img_random], keys=["RALIS", "Entropy", "BALD", "Random"])

In [33]:
df_img_al_algos

All classes       background          RV         MYO        \
                      mean   std       mean   std  mean   std  mean   std   
        budget                                                              
RALIS   64           0.321 0.086      0.981 0.003 0.074 0.102 0.065 0.122   
        128          0.378 0.114      0.982 0.003 0.077 0.124 0.119 0.123   
        592          0.498 0.233      0.985 0.005 0.266 0.282 0.323 0.297   
        960          0.595 0.228      0.988 0.006 0.429 0.263 0.360 0.330   
        1184         0.571 0.295      0.986 0.010 0.367 0.338 0.419 0.373   
        1424         0.596 0.246      0.988 0.006 0.404 0.320 0.392 0.309   
        1904         0.651 0.241      0.990 0.006 0.469 0.290 0.487 0.343   
        2384         0.708 0.214      0.991 0.005 0.522 0.300 0.563 0.333   
        3568         0.746 0.246      0.992 0.007 0.612 0.346 0.621 0.350   
Entropy 64           0.339 0.176      0.982 0.004 0.114 0.227 0.086 0.192   
        128          0.379 0.183      0.982 0.005 0.151 0.207 0.127 0.192   
        592          0.676 0.223      0.990 0.006 0.476 0.270 0.532 0.274   
        960          0.690 0.251      0.990 0.006 0.546 0.310 0.548 0.310   
        1184         0.722 0.156      0.991 0.004 0.588 0.206 0.557 0.222   
        1424         0.726 0.228      0.991 0.007 0.578 0.307 0.585 0.312   
        1904         0.700 0.275      0.991 0.007 0.565 0.349 0.556 0.360   
        2384         0.807 0.097      0.994 0.003 0.657 0.151 0.703 0.183   
        3568         0.789 0.230      0.995 0.006 0.696 0.313 0.675 0.333   
BALD    64           0.456 0.070      0.985 0.001 0.175 0.188 0.204 0.099   
        128          0.583 0.077      0.988 0.001 0.310 0.096 0.373 0.155   
        592          0.780 0.026      0.993 0.001 0.637 0.105 0.643 0.048   
        960          0.824 0.014      0.995 0.001 0.698 0.063 0.725 0.020   
        1184         0.822 0.016      0.994 0.000 0.711 0.063 0.715 0.038   
        1424         0.839 0.020      0.995 0.001 0.726 0.047 0.753 0.029   
        1904         0.861 0.016      0.996 0.001 0.754 0.032 0.791 0.028   
        2384         0.883 0.009      0.996 0.000 0.802 0.026 0.820 0.010   
        3568         0.902 0.005      0.997 0.000 0.842 0.010 0.847 0.007   
Random  64           0.272 0.022      0.980 0.000 0.033 0.056 0.000 0.000   
        128          0.267 0.028      0.980 0.001 0.000 0.000 0.001 0.002   
        592          0.265 0.013      0.980 0.000 0.001 0.001 0.001 0.002   
        960          0.262 0.015      0.980 0.001 0.034 0.073 0.000 0.000   
        1184         0.275 0.014      0.980 0.001 0.036 0.081 0.003 0.007   
        1424         0.274 0.020      0.981 0.001 0.007 0.010 0.002 0.003   
        1904         0.313 0.024      0.982 0.001 0.000 0.000 0.002 0.003   
        2384         0.317 0.042      0.981 0.001 0.034 0.060 0.053 0.053   
        3568         0.368 0.036      0.982 0.001 0.146 0.197 0.091 0.060   

                  LV        
                mean   std  
        budget              
RALIS   64     0.163 0.233  
        128    0.336 0.277  
        592    0.417 0.376  
        960    0.602 0.342  
        1184   0.511 0.466  
        1424   0.601 0.356  
        1904   0.658 0.340  
        2384   0.755 0.218  
        3568   0.758 0.281  
Entropy 64     0.176 0.291  
        128    0.254 0.331  
        592    0.704 0.345  
        960    0.676 0.379  
        1184   0.753 0.198  
        1424   0.750 0.290  
        1904   0.688 0.395  
        2384   0.876 0.066  
        3568   0.792 0.268  
BALD    64     0.458 0.086  
        128    0.661 0.110  
        592    0.847 0.034  
        960    0.877 0.013  
        1184   0.869 0.025  
        1424   0.880 0.029  
        1904   0.904 0.017  
        2384   0.912 0.006  
        3568   0.923 0.005  
Random  64     0.074 0.102  
        128    0.087 0.112  
        592    0.079 0.051  
        960    0.034 0.028  
        1184   0.080 0.06

In [34]:
cols = [i for i in df_img_al_algos.columns.values]
cols = np.unique(cols)
print("cols: ", cols)
#cols = np.unique(cols)
idx = [0,1,3,4,2]
cols = cols[idx]

cols:  ['All classes' 'LV' 'MYO' 'RV' 'background' 'mean' 'std']


In [35]:
df_new = pd.DataFrame(columns=cols)
for c in cols:
    means = df_img_al_algos[c]['mean'].values
    stds = df_img_al_algos[c]['std'].values
    newcol = [f'{mean:.3f}(±{std:.3f})' for mean, std in zip(means, stds)]
    df_new[c] = newcol
    #df_lr_01.drop(c, axis=1, inplace=True)
    #df_lr_01[c] = newcol
    
df_new = pd.DataFrame(columns=cols)
for c in cols:
    means = df_img_al_algos[c]['mean'].values
    stds = df_img_al_algos[c]['std'].values
    newcol = [f'{mean:.3f}(±{std:.3f})' for mean, std in zip(means, stds)]
    df_new[c] = newcol
    df_img_al_algos.drop(c, axis=1, inplace=True)
    df_img_al_algos[c] = newcol
del df_img_al_algos['background']
#df_lr_01 = df_lr_01.rename(columns={"Mean DSC":"All Classes"})

/home/carina/.local/lib/python3.8/site-packages/pandas/core/generic.py:4153: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


In [36]:
df_img_al_algos

All classes             LV             RV            MYO
                                                                          
        budget                                                            
RALIS   64      0.321(±0.086)  0.163(±0.233)  0.074(±0.102)  0.065(±0.122)
        128     0.378(±0.114)  0.336(±0.277)  0.077(±0.124)  0.119(±0.123)
        592     0.498(±0.233)  0.417(±0.376)  0.266(±0.282)  0.323(±0.297)
        960     0.595(±0.228)  0.602(±0.342)  0.429(±0.263)  0.360(±0.330)
        1184    0.571(±0.295)  0.511(±0.466)  0.367(±0.338)  0.419(±0.373)
        1424    0.596(±0.246)  0.601(±0.356)  0.404(±0.320)  0.392(±0.309)
        1904    0.651(±0.241)  0.658(±0.340)  0.469(±0.290)  0.487(±0.343)
        2384    0.708(±0.214)  0.755(±0.218)  0.522(±0.300)  0.563(±0.333)
        3568    0.746(±0.246)  0.758(±0.281)  0.612(±0.346)  0.621(±0.350)
Entropy 64      0.339(±0.176)  0.176(±0.291)  0.114(±0.227)  0.086(±0.192)
        128     0.379(±0.183)  0.254(±0.331)  0.151(±0.207)  0.127(±0.192)
        592     0.676(±0.223)  0.704(±0.345)  0.476(±0.270)  0.532(±0.274)
        960     0.690(±0.251)  0.676(±0.379)  0.546(±0.310)  0.548(±0.310)
        1184    0.722(±0.156)  0.753(±0.198)  0.588(±0.206)  0.557(±0.222)
        1424    0.726(±0.228)  0.750(±0.290)  0.578(±0.307)  0.585(±0.312)
        1904    0.700(±0.275)  0.688(±0.395)  0.565(±0.349)  0.556(±0.360)
        2384    0.807(±0.097)  0.876(±0.066)  0.657(±0.151)  0.703(±0.183)
        3568    0.789(±0.230)  0.792(±0.268)  0.696(±0.313)  0.675(±0.333)
BALD    64      0.456(±0.070)  0.458(±0.086)  0.175(±0.188)  0.204(±0.099)
        128     0.583(±0.077)  0.661(±0.110)  0.310(±0.096)  0.373(±0.155)
        592     0.780(±0.026)  0.847(±0.034)  0.637(±0.105)  0.643(±0.048)
        960     0.824(±0.014)  0.877(±0.013)  0.698(±0.063)  0.725(±0.020)
        1184    0.822(±0.016)  0.869(±0.025)  0.711(±0.063)  0.715(±0.038)
        1424    0.839(±0.020)  0.880(±0.029)  0.726(±0.047)  0.753(±0.029)
        1904    0.861(±0.016)  0.904(±0.017)  0.754(±0.032)  0.791(±0.028)
        2384    0.883(±0.009)  0.912(±0.006)  0.802(±0.026)  0.820(±0.010)
        3568    0.902(±0.005)  0.923(±0.005)  0.842(±0.010)  0.847(±0.007)
Random  64      0.272(±0.022)  0.074(±0.102)  0.033(±0.056)  0.000(±0.000)
        128     0.267(±0.028)  0.087(±0.112)  0.000(±0.000)  0.001(±0.002)
        592     0.265(±0.013)  0.079(±0.051)  0.001(±0.001)  0.001(±0.002)
        960     0.262(±0.015)  0.034(±0.028)  0.034(±0.073)  0.000(±0.000)
        1184    0.275(±0.014)  0.080(±0.064)  0.036(±0.081)  0.003(±0.007)
        1424    0.274(±0.020)  0.105(±0.073)  0.007(±0.010)  0.002(±0.003)
        1904    0.313(±0.024)  0.268(±0.098)  0.000(±0.000)  0.002(±0.003)
        2384    0.317(±0.042)  0.201(±0.069)  0.034(±0.060)  0.053(±0.053)
        3568    0.368(±0.036)  0.254(±0.186)  0.146(±0.197)  0.091(±0.060)

In [55]:
df_img_al_algos

All classes             LV             RV            MYO
                                                                          
        budget                                                            
RALIS   64      0.538(±0.167)  0.493(±0.279)  0.372(±0.219)  0.300(±0.183)
        128     0.666(±0.036)  0.681(±0.037)  0.547(±0.037)  0.447(±0.091)
        592     0.806(±0.013)  0.859(±0.014)  0.686(±0.033)  0.685(±0.030)
        960     0.860(±0.008)  0.901(±0.011)  0.794(±0.009)  0.749(±0.019)
        1184    0.876(±0.011)  0.909(±0.006)  0.809(±0.030)  0.788(±0.018)
        1424    0.885(±0.007)  0.915(±0.004)  0.816(±0.027)  0.814(±0.009)
        1904    0.903(±0.004)  0.921(±0.005)  0.850(±0.007)  0.843(±0.007)
        2384    0.909(±0.002)  0.927(±0.004)  0.855(±0.007)  0.857(±0.002)
        3568    0.909(±0.004)  0.930(±0.002)  0.857(±0.005)  0.852(±0.008)
Entropy 64      0.383(±0.158)  0.301(±0.299)  0.164(±0.234)  0.085(±0.141)
        128     0.610(±0.064)  0.618(±0.119)  0.496(±0.059)  0.337(±0.100)
        592     0.819(±0.018)  0.859(±0.020)  0.760(±0.028)  0.663(±0.037)
        960     0.840(±0.027)  0.873(±0.036)  0.793(±0.026)  0.698(±0.050)
        1184    0.860(±0.014)  0.891(±0.015)  0.815(±0.018)  0.737(±0.028)
        1424    0.878(±0.005)  0.906(±0.007)  0.825(±0.009)  0.785(±0.012)
        1904    0.890(±0.011)  0.912(±0.009)  0.841(±0.016)  0.810(±0.021)
        2384    0.908(±0.002)  0.924(±0.003)  0.860(±0.006)  0.851(±0.005)
        3568    0.913(±0.002)  0.932(±0.002)  0.861(±0.005)  0.860(±0.006)
BALD    64      0.601(±0.105)  0.637(±0.093)  0.420(±0.227)  0.359(±0.176)
        128     0.697(±0.073)  0.725(±0.094)  0.563(±0.131)  0.511(±0.115)
        592     0.823(±0.018)  0.854(±0.022)  0.772(±0.070)  0.671(±0.024)
        960     0.859(±0.011)  0.884(±0.016)  0.822(±0.007)  0.734(±0.026)
        1184    0.873(±0.014)  0.904(±0.008)  0.828(±0.021)  0.766(±0.031)
        1424    0.882(±0.012)  0.905(±0.015)  0.836(±0.011)  0.788(±0.032)
        1904    0.900(±0.005)  0.920(±0.003)  0.854(±0.007)  0.829(±0.008)
        2384    0.909(±0.002)  0.927(±0.002)  0.859(±0.006)  0.852(±0.005)
        3568    0.909(±0.004)  0.927(±0.006)  0.857(±0.006)  0.853(±0.006)
Random  64      0.301(±0.045)  0.137(±0.165)  0.073(±0.067)  0.013(±0.027)
        128     0.321(±0.046)  0.169(±0.138)  0.101(±0.108)  0.030(±0.023)
        592     0.422(±0.067)  0.343(±0.076)  0.192(±0.146)  0.168(±0.096)
        960     0.382(±0.057)  0.289(±0.126)  0.164(±0.101)  0.093(±0.091)
        1184    0.479(±0.109)  0.410(±0.132)  0.277(±0.225)  0.244(±0.092)
        1424    0.469(±0.097)  0.375(±0.173)  0.310(±0.155)  0.207(±0.092)
        1904    0.591(±0.061)  0.615(±0.139)  0.420(±0.106)  0.344(±0.062)
        2384    0.617(±0.067)  0.595(±0.192)  0.527(±0.112)  0.359(±0.097)
        3568    0.716(±0.023)  0.751(±0.076)  0.558(±0.119)  0.565(±0.052)

In [56]:
print(df_img_al_algos.to_latex(index=True))

\begin{tabular}{llllll}
\toprule
       &      &    All classes &             LV &             RV &            MYO \\
       &      \\
{} & budget &                &                &                &                \\
\midrule
RALIS & 64 &  0.538(±0.167) &  0.493(±0.279) &  0.372(±0.219) &  0.300(±0.183) \\
       & 128 &  0.666(±0.036) &  0.681(±0.037) &  0.547(±0.037) &  0.447(±0.091) \\
       & 592 &  0.806(±0.013) &  0.859(±0.014) &  0.686(±0.033) &  0.685(±0.030) \\
       & 960 &  0.860(±0.008) &  0.901(±0.011) &  0.794(±0.009) &  0.749(±0.019) \\
       & 1184 &  0.876(±0.011) &  0.909(±0.006) &  0.809(±0.030) &  0.788(±0.018) \\
       & 1424 &  0.885(±0.007) &  0.915(±0.004) &  0.816(±0.027) &  0.814(±0.009) \\
       & 1904 &  0.903(±0.004) &  0.921(±0.005) &  0.850(±0.007) &  0.843(±0.007) \\
       & 2384 &  0.909(±0.002) &  0.927(±0.004) &  0.855(±0.007) &  0.857(±0.002) \\
       & 3568 &  0.909(±0.004) &  0.930(±0.002) &  0.857(±0.005) &  0.852(±0.008) \\
Entropy & 64 &

## All classes mean and std

In [38]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [39]:
random_mean = np.array(df_img_random["All classes"]["mean"].values)
random_sd = np.array(df_img_random["All classes"]["std"].values)

In [40]:
bald_mean = np.array(df_img_bald["All classes"]["mean"].values)
bald_sd = np.array(df_img_bald["All classes"]["std"].values)

In [41]:
entropy_mean = np.array(df_img_entropy["All classes"]["mean"].values)
entropy_sd = np.array(df_img_entropy["All classes"]["std"].values)

In [42]:
ralis_mean = np.array(df_img_ralis["All classes"]["mean"].values)
ralis_sd = np.array(df_img_ralis["All classes"]["std"].values)

In [43]:
random_mean

array([0.301, 0.321, 0.422, 0.382, 0.479, 0.469, 0.591, 0.617, 0.716])

In [44]:
random_sd

array([0.045, 0.046, 0.067, 0.057, 0.109, 0.097, 0.061, 0.067, 0.023])

In [45]:
entropy_mean

array([0.383, 0.610, 0.819, 0.840, 0.860, 0.878, 0.890, 0.908, 0.913])

In [46]:
entropy_sd

array([0.158, 0.064, 0.018, 0.027, 0.014, 0.005, 0.011, 0.002, 0.002])

In [47]:
bald_mean

array([0.601, 0.697, 0.823, 0.859, 0.873, 0.882, 0.900, 0.909, 0.909])

In [48]:
bald_sd

array([0.105, 0.073, 0.018, 0.011, 0.014, 0.012, 0.005, 0.002, 0.004])

In [49]:
ralis_mean

array([0.538, 0.666, 0.806, 0.860, 0.876, 0.885, 0.903, 0.909, 0.909])

In [50]:
ralis_sd

array([0.167, 0.036, 0.013, 0.008, 0.011, 0.007, 0.004, 0.002, 0.004])