In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [2]:
# read log file baselines and ralis

In [3]:
# path to logs
path = '/mnt/qb/baumgartner/cschmidt77_data/_FINAL_brats18_exp6/'

In [4]:
exp_6_brats = os.listdir(path)

In [5]:
exp_6_brats

['2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.001_123',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.001_20',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.001_234',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.001_55',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.001_77',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.01_123',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.01_20',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.01_234',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.01_55',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.01_77',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.05_123',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.05_20',
 '2021-10-20-supervised-brats18-allPatients_RIRD_Image

In [7]:
data_frame_lists = []
for exp in exp_6_brats: 
    exp_path = path + exp + '/Mean_3D_DSC.txt'
    if os.path.isfile(exp_path): 
        if 'DT3' in exp:
            names = ["All classes", "background", "NCR/NET", "ED", "ET", "Experiment", "seed", "Augmentation", "lr"]
            data = pd.read_csv(exp_path, nrows=1, skiprows=1, names=names, sep ='\t')
            data["Experiment"] = exp
            data = data[["Experiment", "seed", "All classes", "background", "NCR/NET", "ED", "ET"]]
    #         if 'supervised' in exp:
            data['lr'] = exp.split('_')[-2]
            data['Augmentation'] = exp.split('_')[-5]
            data['seed'] = exp.split('_')[-1]
            data_frame_lists.append(data)

frame = pd.concat(data_frame_lists, axis=0, ignore_index=True)

In [8]:
frame

Experiment seed  All classes  \
0  2021-11-05-supervised-brats18_DT3_RIRD_ImageNe...  123     0.704732   
1  2021-11-05-supervised-brats18_DT3_RIRD_ImageNe...   20     0.710428   
2  2021-11-05-supervised-brats18_DT3_RIRD_ImageNe...  234     0.699612   
3  2021-11-05-supervised-brats18_DT3_RIRD_ImageNe...   55     0.706627   
4  2021-11-05-supervised-brats18_DT3_RIRD_ImageNe...   77     0.703423   
5  2021-11-05-supervised-brats18_DT3_stdAug_Image...  123     0.710671   
6  2021-11-05-supervised-brats18_DT3_stdAug_Image...   20     0.714274   
7  2021-11-05-supervised-brats18_DT3_stdAug_Image...  234     0.705275   
8  2021-11-05-supervised-brats18_DT3_stdAug_Image...   55     0.698400   
9  2021-11-05-supervised-brats18_DT3_stdAug_Image...   77     0.700772   

   background   NCR/NET        ED        ET    lr Augmentation  
0    0.994960  0.680741  0.007081  0.524368  0.01         RIRD  
1    0.995025  0.683210  0.000000  0.542765  0.01         RIRD  
2    0.993549  0.659424  0.000000  0.531555  0.01         RIRD  
3    0.994651  0.667001  0.006510  0.545141  0.01         RIRD  
4    0.994307  0.665184  0.005274  0.536673  0.01         RIRD  
5    0.995105  0.684019  0.052300  0.531723  0.01       stdAug  
6    0.994838  0.679079  0.000000  0.560313  0.01       stdAug  
7    0.994317  0.673732  0.000000  0.535585  0.01       stdAug  
8    0.994286  0.670309  0.007022  0.514109  0.01       stdAug  
9    0.993869  0.663688  0.006506  0.529460  0.01       stdAug

In [9]:
frame_new = frame.drop(columns="Experiment")

In [10]:
pd.options.display.float_format = "{:,.3f}".format

In [11]:
frame_new.sort_values(by=['All classes'], ascending=False)

seed  All classes  background  NCR/NET    ED    ET    lr Augmentation
6   20        0.714       0.995    0.679 0.000 0.560  0.01       stdAug
5  123        0.711       0.995    0.684 0.052 0.532  0.01       stdAug
1   20        0.710       0.995    0.683 0.000 0.543  0.01         RIRD
3   55        0.707       0.995    0.667 0.007 0.545  0.01         RIRD
7  234        0.705       0.994    0.674 0.000 0.536  0.01       stdAug
0  123        0.705       0.995    0.681 0.007 0.524  0.01         RIRD
4   77        0.703       0.994    0.665 0.005 0.537  0.01         RIRD
9   77        0.701       0.994    0.664 0.007 0.529  0.01       stdAug
2  234        0.700       0.994    0.659 0.000 0.532  0.01         RIRD
8   55        0.698       0.994    0.670 0.007 0.514  0.01       stdAug

## Standard Augmentation lr 0.01

In [12]:
imgStd01 = frame_new.loc[(frame_new['Augmentation'] == 'stdAug') & (frame_new['lr'] == '0.01')]

In [13]:
imgStd01 = imgStd01.groupby(['Augmentation', 'lr']).agg({'All classes': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'NCR/NET':['mean', 'std'], 'ED':['mean', 'std'], 'ET':['mean', 'std']})

In [14]:
imgStd01

All classes       background       NCR/NET          ED  \
                         mean   std       mean   std    mean   std  mean   
Augmentation lr                                                            
stdAug       0.01       0.706 0.007      0.994 0.000   0.674 0.008 0.013   

                           ET        
                    std  mean   std  
Augmentation lr                      
stdAug       0.01 0.022 0.534 0.017

## RIRD lr 0.01

In [15]:
imgRIRD01 = frame_new.loc[(frame_new['Augmentation'] == 'RIRD') & (frame_new['lr'] == '0.01')]

In [16]:
imgRIRD01 = imgRIRD01.groupby(['Augmentation', 'lr']).agg({'All classes': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'NCR/NET':['mean', 'std'], 'ED':['mean', 'std'], 'ET':['mean', 'std']})

## Concatenated

In [17]:
df_supervised = pd.concat([imgStd01,imgRIRD01])#, keys=["Std-0.001", "Std-0.01", "Std-0.05", "RI/RD-0.001", "RI/RD-0.01", "RI/RD-0.05"])

In [18]:
df_supervised

All classes       background       NCR/NET          ED  \
                         mean   std       mean   std    mean   std  mean   
Augmentation lr                                                            
stdAug       0.01       0.706 0.007      0.994 0.000   0.674 0.008 0.013   
RIRD         0.01       0.705 0.004      0.994 0.001   0.671 0.010 0.004   

                           ET        
                    std  mean   std  
Augmentation lr                      
stdAug       0.01 0.022 0.534 0.017  
RIRD         0.01 0.004 0.536 0.008

In [19]:
df_img_al_algos = df_supervised

In [20]:
np.unique(df_img_al_algos.columns.values)

array([('All classes', 'mean'), ('All classes', 'std'), ('ED', 'mean'),
       ('ED', 'std'), ('ET', 'mean'), ('ET', 'std'), ('NCR/NET', 'mean'),
       ('NCR/NET', 'std'), ('background', 'mean'), ('background', 'std')],
      dtype=object)

In [21]:
cols = [i for i in df_img_al_algos.columns.values]
cols = np.unique(cols)
print("cols: ", cols)
#cols = np.unique(cols)
idx = [0,3,1,2,4]
cols = cols[idx]

cols:  ['All classes' 'ED' 'ET' 'NCR/NET' 'background' 'mean' 'std']


In [22]:
df_new = pd.DataFrame(columns=cols)
for c in cols:
    means = df_img_al_algos[c]['mean'].values
    stds = df_img_al_algos[c]['std'].values
    newcol = [f'{mean:.3f}(±{std:.3f})' for mean, std in zip(means, stds)]
    df_new[c] = newcol
    #df_lr_01.drop(c, axis=1, inplace=True)
    #df_lr_01[c] = newcol
    
df_new = pd.DataFrame(columns=cols)
for c in cols:
    means = df_img_al_algos[c]['mean'].values
    stds = df_img_al_algos[c]['std'].values
    newcol = [f'{mean:.3f}(±{std:.3f})' for mean, std in zip(means, stds)]
    df_new[c] = newcol
    df_img_al_algos.drop(c, axis=1, inplace=True)
    df_img_al_algos[c] = newcol
del df_img_al_algos['background']
#df_lr_01 = df_lr_01.rename(columns={"Mean DSC":"All Classes"})

/home/carina/.local/lib/python3.8/site-packages/pandas/core/generic.py:4153: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


In [23]:
df_img_al_algos

All classes        NCR/NET             ED             ET
                                                                             
Augmentation lr                                                              
stdAug       0.01  0.706(±0.007)  0.674(±0.008)  0.013(±0.022)  0.534(±0.017)
RIRD         0.01  0.705(±0.004)  0.671(±0.010)  0.004(±0.004)  0.536(±0.008)

In [24]:
print(df_img_al_algos.to_latex(index=True))

\begin{tabular}{llllll}
\toprule
     &      &    All classes &        NCR/NET &             ED &             ET \\
     &      \\
Augmentation & lr &                &                &                &                \\
\midrule
stdAug & 0.01 &  0.706(±0.007) &  0.674(±0.008) &  0.013(±0.022) &  0.534(±0.017) \\
RIRD & 0.01 &  0.705(±0.004) &  0.671(±0.010) &  0.004(±0.004) &  0.536(±0.008) \\
\bottomrule
\end{tabular}



## All classes mean and std

In [84]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [85]:
random_mean = np.array(df_img_random["All classes"]["mean"].values)
random_sd = np.array(df_img_random["All classes"]["std"].values)

In [86]:
bald_mean = np.array(df_img_bald["All classes"]["mean"].values)
bald_sd = np.array(df_img_bald["All classes"]["std"].values)

In [87]:
entropy_mean = np.array(df_img_entropy["All classes"]["mean"].values)
entropy_sd = np.array(df_img_entropy["All classes"]["std"].values)

In [88]:
ralis_mean = np.array(df_img_ralis["All classes"]["mean"].values)
ralis_sd = np.array(df_img_ralis["All classes"]["std"].values)

In [89]:
random_mean

array([0.367, 0.357, 0.377, 0.395, 0.464, 0.490])

In [90]:
random_sd

array([0.021, 0.009, 0.018, 0.036, 0.060, 0.045])

In [91]:
entropy_mean

array([0.350, 0.359, 0.402, 0.467, 0.503, 0.530])

In [92]:
entropy_sd

array([0.000, 0.012, 0.017, 0.053, 0.018, 0.009])

In [93]:
bald_mean

array([0.350, 0.373, 0.409, 0.364, 0.439, 0.536])

In [94]:
bald_sd

array([0.000, 0.023, 0.044, 0.162, 0.161, 0.028])

In [95]:
ralis_mean

array([0.351, 0.404, 0.480, 0.479, 0.519, 0.553])

In [96]:
ralis_sd

array([0.001, 0.030, 0.050, 0.015, 0.027, 0.016])