In [3]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [4]:
# read log file baselines and ralis

In [5]:
# path to logs
path = '/mnt/qb/baumgartner/cschmidt77_data/_FINAL_brats18_exp6/'

In [10]:
exp_6_brats = os.listdir(path)

In [35]:
exp_6_brats

['2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.001_123',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.001_20',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.001_234',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.001_55',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.001_77',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.01_123',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.01_20',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.01_234',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.01_55',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.01_77',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.05_123',
 '2021-10-20-supervised-brats18-allPatients_RIRD_ImageNetBackbone_lr0.05_20',
 '2021-10-20-supervised-brats18-allPatients_RIRD_Image

In [41]:
data_frame_lists = []
for exp in exp_6_brats: 
    exp_path = path + exp + '/Mean_3D_DSC.txt'
    if os.path.isfile(exp_path): 
        if not 'supervised' in exp:
            names = ["All classes", "background", "NCR/NET", "ED", "ET", "Experiment", "seed", "budget"]
            data = pd.read_csv(exp_path, nrows=1, skiprows=1, names=names, sep ='\t')
            data["Experiment"] = exp
            data = data[["Experiment", "seed", "budget", "All classes", "background", "NCR/NET", "ED", "ET"]]
    #         if 'supervised' in exp:
    #             data['al-algo'] = 'supervised'
    #             data['budget'] = '-'
    #         else:
            data['budget'] = exp.split('_')[-3]    
            if 'ralis' in exp:
                data['al-algo'] = 'ralis'
            elif 'bald' in exp:
                data['al-algo'] = 'bald'
            elif 'random' in exp:
                data['al-algo'] = 'random'
            elif 'entropy' in exp:
                data['al-algo'] = 'entropy'
            else: #supervised all patients
                print("supervised or something went wrong")       
            data['seed'] = exp.split('_')[-1]
            data_frame_lists.append(data)

frame = pd.concat(data_frame_lists, axis=0, ignore_index=True)

In [42]:
frame

Experiment seed budget  \
0    2021-11-04-brats18_ImageNetBackbone_baseline_b...  123  17792   
1    2021-11-04-brats18_ImageNetBackbone_baseline_b...   20  17792   
2    2021-11-04-brats18_ImageNetBackbone_baseline_b...  234  17792   
3    2021-11-04-brats18_ImageNetBackbone_baseline_b...   55  17792   
4    2021-11-04-brats18_ImageNetBackbone_baseline_b...   77  17792   
..                                                 ...  ...    ...   
115  2021-11-06-brats18_ImageNetBackbone_baseline_r...  123  35584   
116  2021-11-06-brats18_ImageNetBackbone_baseline_r...   20  35584   
117  2021-11-06-brats18_ImageNetBackbone_baseline_r...  234  35584   
118  2021-11-06-brats18_ImageNetBackbone_baseline_r...   55  35584   
119  2021-11-06-brats18_ImageNetBackbone_baseline_r...   77  35584   

     All classes  background  NCR/NET    ED    ET al-algo  
0          0.156       0.407    0.020 0.000 0.022    bald  
1          0.542       0.994    0.343 0.075 0.295    bald  
2          0.468       0.992    0.203 0.046 0.188    bald  
3          0.534       0.993    0.346 0.082 0.262    bald  
4          0.493       0.992    0.249 0.072 0.221    bald  
..           ...         ...      ...   ...   ...     ...  
115        0.460       0.992    0.206 0.111 0.143  random  
116        0.513       0.993    0.347 0.071 0.192  random  
117        0.473       0.992    0.237 0.114 0.154  random  
118        0.556       0.993    0.288 0.021 0.407  random  
119        0.446       0.992    0.141 0.018 0.180  random  

[120 rows x 9 columns]

In [43]:
frame_new = frame.drop(columns="Experiment")

In [44]:
pd.options.display.float_format = "{:,.3f}".format

In [47]:
frame_new.sort_values(by=['All classes'], ascending=False)

seed budget  All classes  background  NCR/NET    ED    ET  al-algo
102  234  35584        0.565       0.994    0.374 0.091 0.337     bald
111   20  35584        0.564       0.994    0.382 0.101 0.323    ralis
110  123  35584        0.561       0.994    0.377 0.174 0.300    ralis
112  234  35584        0.557       0.994    0.364 0.083 0.323    ralis
114   77  35584        0.557       0.994    0.370 0.056 0.319    ralis
..   ...    ...          ...         ...      ...   ...   ...      ...
45   123     64        0.350       0.990    0.000 0.000 0.000  entropy
46    20     64        0.350       0.990    0.000 0.000 0.000  entropy
47   234     64        0.350       0.990    0.000 0.000 0.000  entropy
0    123  17792        0.156       0.407    0.020 0.000 0.022     bald
10   123   3584        0.088       0.243    0.001 0.000 0.005     bald

[120 rows x 8 columns]

In [48]:
frame_new['budget']

0      17792
1      17792
2      17792
3      17792
4      17792
       ...  
115    35584
116    35584
117    35584
118    35584
119    35584
Name: budget, Length: 120, dtype: object

In [49]:
frame_new['al-algo'] == 'bald'

0       True
1       True
2       True
3       True
4       True
       ...  
115    False
116    False
117    False
118    False
119    False
Name: al-algo, Length: 120, dtype: bool

In [50]:
frame_new['budget'].unique()

array(['17792', '1792', '3584', '384', '64', '35584'], dtype=object)

## BALD

In [51]:
for budget in frame_new['budget'].unique():
    # create data frames for different budgets names e.g. imgStd01_budget_128
    df_img_bald = frame_new.loc[(frame_new['al-algo'] == 'bald') & (frame_new['budget'] == budget)]
    globals()['img_bald_%s' % budget] = df_img_bald.groupby(['budget']).agg({'All classes': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'NCR/NET':['mean', 'std'], 'ED':['mean', 'std'], 'ET':['mean', 'std']})

In [53]:
img_bald_17792

All classes       background       NCR/NET          ED          ET  \
              mean   std       mean   std    mean   std  mean   std  mean   
budget                                                                      
17792        0.439 0.161      0.876 0.262   0.232 0.134 0.055 0.034 0.197   

              
         std  
budget        
17792  0.106

## Entropy

In [54]:
for budget in frame_new['budget'].unique():
    # create data frames for different budgets names e.g. imgStd01_budget_128
    df_img_entropy = frame_new.loc[(frame_new['al-algo'] == 'entropy') & (frame_new['budget'] == budget)]
    globals()['img_entropy_%s' % budget] = df_img_entropy.groupby(['budget']).agg({'All classes': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'NCR/NET':['mean', 'std'], 'ED':['mean', 'std'], 'ET':['mean', 'std']})

In [56]:
img_entropy_17792

All classes       background       NCR/NET          ED          ET  \
              mean   std       mean   std    mean   std  mean   std  mean   
budget                                                                      
17792        0.503 0.018      0.993 0.000   0.271 0.028 0.081 0.049 0.230   

              
         std  
budget        
17792  0.035

## Random

In [57]:
for budget in frame_new['budget'].unique():
    # create data frames for different budgets names e.g. imgStd01_budget_128
    df_img_random = frame_new.loc[(frame_new['al-algo'] == 'random') & (frame_new['budget'] == budget)]
    globals()['img_random_%s' % budget] = df_img_random.groupby(['budget']).agg({'All classes': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'NCR/NET':['mean', 'std'], 'ED':['mean', 'std'], 'ET':['mean', 'std']})

In [58]:
img_random_17792

All classes       background       NCR/NET          ED          ET  \
              mean   std       mean   std    mean   std  mean   std  mean   
budget                                                                      
17792        0.464 0.060      0.992 0.001   0.179 0.090 0.063 0.049 0.194   

              
         std  
budget        
17792  0.124

## RALIS

In [59]:
for budget in frame_new['budget'].unique():
    # create data frames for different budgets names e.g. imgStd01_budget_128
    df_img_ralis = frame_new.loc[(frame_new['al-algo'] == 'ralis') & (frame_new['budget'] == budget)]
    globals()['img_ralis_%s' % budget] = df_img_ralis.groupby(['budget']).agg({'All classes': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'NCR/NET':['mean', 'std'], 'ED':['mean', 'std'], 'ET':['mean', 'std']})

In [60]:
img_ralis_17792

All classes       background       NCR/NET          ED          ET  \
              mean   std       mean   std    mean   std  mean   std  mean   
budget                                                                      
17792        0.519 0.027      0.993 0.000   0.290 0.029 0.081 0.023 0.265   

              
         std  
budget        
17792  0.068

## Concatenated for al-algorithms

In [61]:
# budgets '17792', '1792', '3584', '384', '64', '35584'

In [64]:
budgets = frame_new['budget'].unique()

In [65]:
budgets

array(['17792', '1792', '3584', '384', '64', '35584'], dtype=object)

## Random

In [66]:
df_img_random = pd.concat([img_random_64, img_random_384, img_random_1792,
                           img_random_3584, img_random_17792, img_random_35584])

In [67]:
df_img_random

All classes       background       NCR/NET          ED          ET  \
              mean   std       mean   std    mean   std  mean   std  mean   
budget                                                                      
64           0.367 0.021      0.991 0.000   0.051 0.074 0.022 0.037 0.000   
384          0.357 0.009      0.991 0.001   0.002 0.004 0.022 0.028 0.015   
1792         0.377 0.018      0.991 0.001   0.033 0.031 0.077 0.061 0.038   
3584         0.395 0.036      0.991 0.001   0.062 0.059 0.031 0.035 0.084   
17792        0.464 0.060      0.992 0.001   0.179 0.090 0.063 0.049 0.194   
35584        0.490 0.045      0.993 0.000   0.244 0.079 0.067 0.047 0.215   

              
         std  
budget        
64     0.000  
384    0.033  
1792   0.042  
3584   0.076  
17792  0.124  
35584  0.109

## Entropy

In [68]:
df_img_entropy = pd.concat([img_entropy_64, img_entropy_384, img_entropy_1792,
                           img_entropy_3584, img_entropy_17792, img_entropy_35584])

In [69]:
df_img_entropy

All classes       background       NCR/NET          ED          ET  \
              mean   std       mean   std    mean   std  mean   std  mean   
budget                                                                      
64           0.350 0.000      0.990 0.000   0.000 0.000 0.000 0.000 0.000   
384          0.359 0.012      0.990 0.000   0.009 0.013 0.011 0.010 0.018   
1792         0.402 0.017      0.991 0.000   0.087 0.023 0.045 0.037 0.077   
3584         0.467 0.053      0.992 0.001   0.211 0.107 0.110 0.075 0.161   
17792        0.503 0.018      0.993 0.000   0.271 0.028 0.081 0.049 0.230   
35584        0.530 0.009      0.993 0.000   0.323 0.026 0.127 0.040 0.260   

              
         std  
budget        
64     0.000  
384    0.030  
1792   0.044  
3584   0.075  
17792  0.035  
35584  0.014

## BALD

In [70]:
df_img_bald = pd.concat([img_bald_64, img_bald_384, img_bald_1792,
                           img_bald_3584, img_bald_17792, img_bald_35584])

In [71]:
df_img_bald

All classes       background       NCR/NET          ED          ET  \
              mean   std       mean   std    mean   std  mean   std  mean   
budget                                                                      
64           0.350 0.000      0.990 0.000   0.000 0.000 0.000 0.000 0.000   
384          0.373 0.023      0.991 0.001   0.033 0.056 0.076 0.049 0.026   
1792         0.409 0.044      0.991 0.001   0.100 0.073 0.103 0.066 0.078   
3584         0.364 0.162      0.842 0.335   0.108 0.096 0.067 0.067 0.105   
17792        0.439 0.161      0.876 0.262   0.232 0.134 0.055 0.034 0.197   
35584        0.536 0.028      0.993 0.000   0.334 0.052 0.098 0.027 0.275   

              
         std  
budget        
64     0.000  
384    0.041  
1792   0.075  
3584   0.118  
17792  0.106  
35584  0.050

## RALIS

In [72]:
df_img_ralis = pd.concat([img_ralis_64, img_ralis_384, img_ralis_1792,
                           img_ralis_3584, img_ralis_17792, img_ralis_35584])

In [73]:
df_img_ralis

All classes       background       NCR/NET          ED          ET  \
              mean   std       mean   std    mean   std  mean   std  mean   
budget                                                                      
64           0.351 0.001      0.990 0.000   0.002 0.004 0.005 0.010 0.000   
384          0.404 0.030      0.991 0.000   0.099 0.057 0.057 0.043 0.073   
1792         0.480 0.050      0.992 0.001   0.230 0.082 0.121 0.078 0.183   
3584         0.479 0.015      0.992 0.000   0.236 0.041 0.074 0.023 0.185   
17792        0.519 0.027      0.993 0.000   0.290 0.029 0.081 0.023 0.265   
35584        0.553 0.016      0.994 0.000   0.361 0.029 0.115 0.051 0.303   

              
         std  
budget        
64     0.000  
384    0.041  
1792   0.082  
3584   0.022  
17792  0.068  
35584  0.031

## Concatenate all al-algos

In [78]:
df_img_al_algos = pd.concat([df_img_ralis, df_img_entropy, df_img_bald, df_img_random], keys=["RALIS", "Entropy", "BALD", "Random"])

In [79]:
df_img_al_algos

All classes       background       NCR/NET          ED        \
                      mean   std       mean   std    mean   std  mean   std   
        budget                                                                
RALIS   64           0.351 0.001      0.990 0.000   0.002 0.004 0.005 0.010   
        384          0.404 0.030      0.991 0.000   0.099 0.057 0.057 0.043   
        1792         0.480 0.050      0.992 0.001   0.230 0.082 0.121 0.078   
        3584         0.479 0.015      0.992 0.000   0.236 0.041 0.074 0.023   
        17792        0.519 0.027      0.993 0.000   0.290 0.029 0.081 0.023   
        35584        0.553 0.016      0.994 0.000   0.361 0.029 0.115 0.051   
Entropy 64           0.350 0.000      0.990 0.000   0.000 0.000 0.000 0.000   
        384          0.359 0.012      0.990 0.000   0.009 0.013 0.011 0.010   
        1792         0.402 0.017      0.991 0.000   0.087 0.023 0.045 0.037   
        3584         0.467 0.053      0.992 0.001   0.211 0.107 0.110 0.075   
        17792        0.503 0.018      0.993 0.000   0.271 0.028 0.081 0.049   
        35584        0.530 0.009      0.993 0.000   0.323 0.026 0.127 0.040   
BALD    64           0.350 0.000      0.990 0.000   0.000 0.000 0.000 0.000   
        384          0.373 0.023      0.991 0.001   0.033 0.056 0.076 0.049   
        1792         0.409 0.044      0.991 0.001   0.100 0.073 0.103 0.066   
        3584         0.364 0.162      0.842 0.335   0.108 0.096 0.067 0.067   
        17792        0.439 0.161      0.876 0.262   0.232 0.134 0.055 0.034   
        35584        0.536 0.028      0.993 0.000   0.334 0.052 0.098 0.027   
Random  64           0.367 0.021      0.991 0.000   0.051 0.074 0.022 0.037   
        384          0.357 0.009      0.991 0.001   0.002 0.004 0.022 0.028   
        1792         0.377 0.018      0.991 0.001   0.033 0.031 0.077 0.061   
        3584         0.395 0.036      0.991 0.001   0.062 0.059 0.031 0.035   
        17792        0.464 0.060      0.992 0.001   0.179 0.090 0.063 0.049   
        35584        0.490 0.045      0.993 0.000   0.244 0.079 0.067 0.047   

                  ET        
                mean   std  
        budget              
RALIS   64     0.000 0.000  
        384    0.073 0.041  
        1792   0.183 0.082  
        3584   0.185 0.022  
        17792  0.265 0.068  
        35584  0.303 0.031  
Entropy 64     0.000 0.000  
        384    0.018 0.030  
        1792   0.077 0.044  
        3584   0.161 0.075  
        17792  0.230 0.035  
        35584  0.260 0.014  
BALD    64     0.000 0.000  
        384    0.026 0.041  
        1792   0.078 0.075  
        3584   0.105 0.118  
        17792  0.197 0.106  
        35584  0.275 0.050  
Random  64     0.000 0.000  
        384    0.015 0.033  
        1792   0.038 0.042  
        3584   0.084 0.076  
        17792  0.194 0.124  
        35584  0.215 0.109

In [80]:
cols = [i for i in df_img_al_algos.columns.values]
cols = np.unique(cols)
print("cols: ", cols)
#cols = np.unique(cols)
idx = [0,3,2,1,4]
cols = cols[idx]

cols:  ['All classes' 'ED' 'ET' 'NCR/NET' 'background' 'mean' 'std']


In [81]:
df_new = pd.DataFrame(columns=cols)
for c in cols:
    means = df_img_al_algos[c]['mean'].values
    stds = df_img_al_algos[c]['std'].values
    newcol = [f'{mean:.3f}(±{std:.3f})' for mean, std in zip(means, stds)]
    df_new[c] = newcol
    #df_lr_01.drop(c, axis=1, inplace=True)
    #df_lr_01[c] = newcol
    
df_new = pd.DataFrame(columns=cols)
for c in cols:
    means = df_img_al_algos[c]['mean'].values
    stds = df_img_al_algos[c]['std'].values
    newcol = [f'{mean:.3f}(±{std:.3f})' for mean, std in zip(means, stds)]
    df_new[c] = newcol
    df_img_al_algos.drop(c, axis=1, inplace=True)
    df_img_al_algos[c] = newcol
del df_img_al_algos['background']
#df_lr_01 = df_lr_01.rename(columns={"Mean DSC":"All Classes"})

/home/carina/.local/lib/python3.8/site-packages/pandas/core/generic.py:4153: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


In [82]:
df_img_al_algos

All classes        NCR/NET             ET             ED
                                                                          
        budget                                                            
RALIS   64      0.351(±0.001)  0.002(±0.004)  0.000(±0.000)  0.005(±0.010)
        384     0.404(±0.030)  0.099(±0.057)  0.073(±0.041)  0.057(±0.043)
        1792    0.480(±0.050)  0.230(±0.082)  0.183(±0.082)  0.121(±0.078)
        3584    0.479(±0.015)  0.236(±0.041)  0.185(±0.022)  0.074(±0.023)
        17792   0.519(±0.027)  0.290(±0.029)  0.265(±0.068)  0.081(±0.023)
        35584   0.553(±0.016)  0.361(±0.029)  0.303(±0.031)  0.115(±0.051)
Entropy 64      0.350(±0.000)  0.000(±0.000)  0.000(±0.000)  0.000(±0.000)
        384     0.359(±0.012)  0.009(±0.013)  0.018(±0.030)  0.011(±0.010)
        1792    0.402(±0.017)  0.087(±0.023)  0.077(±0.044)  0.045(±0.037)
        3584    0.467(±0.053)  0.211(±0.107)  0.161(±0.075)  0.110(±0.075)
        17792   0.503(±0.018)  0.271(±0.028)  0.230(±0.035)  0.081(±0.049)
        35584   0.530(±0.009)  0.323(±0.026)  0.260(±0.014)  0.127(±0.040)
BALD    64      0.350(±0.000)  0.000(±0.000)  0.000(±0.000)  0.000(±0.000)
        384     0.373(±0.023)  0.033(±0.056)  0.026(±0.041)  0.076(±0.049)
        1792    0.409(±0.044)  0.100(±0.073)  0.078(±0.075)  0.103(±0.066)
        3584    0.364(±0.162)  0.108(±0.096)  0.105(±0.118)  0.067(±0.067)
        17792   0.439(±0.161)  0.232(±0.134)  0.197(±0.106)  0.055(±0.034)
        35584   0.536(±0.028)  0.334(±0.052)  0.275(±0.050)  0.098(±0.027)
Random  64      0.367(±0.021)  0.051(±0.074)  0.000(±0.000)  0.022(±0.037)
        384     0.357(±0.009)  0.002(±0.004)  0.015(±0.033)  0.022(±0.028)
        1792    0.377(±0.018)  0.033(±0.031)  0.038(±0.042)  0.077(±0.061)
        3584    0.395(±0.036)  0.062(±0.059)  0.084(±0.076)  0.031(±0.035)
        17792   0.464(±0.060)  0.179(±0.090)  0.194(±0.124)  0.063(±0.049)
        35584   0.490(±0.045)  0.244(±0.079)  0.215(±0.109)  0.067(±0.047)

In [83]:
print(df_img_al_algos.to_latex(index=True))

\begin{tabular}{llllll}
\toprule
       &       &    All classes &        NCR/NET &             ET &             ED \\
       &       \\
{} & budget &                &                &                &                \\
\midrule
RALIS & 64 &  0.351(±0.001) &  0.002(±0.004) &  0.000(±0.000) &  0.005(±0.010) \\
       & 384 &  0.404(±0.030) &  0.099(±0.057) &  0.073(±0.041) &  0.057(±0.043) \\
       & 1792 &  0.480(±0.050) &  0.230(±0.082) &  0.183(±0.082) &  0.121(±0.078) \\
       & 3584 &  0.479(±0.015) &  0.236(±0.041) &  0.185(±0.022) &  0.074(±0.023) \\
       & 17792 &  0.519(±0.027) &  0.290(±0.029) &  0.265(±0.068) &  0.081(±0.023) \\
       & 35584 &  0.553(±0.016) &  0.361(±0.029) &  0.303(±0.031) &  0.115(±0.051) \\
Entropy & 64 &  0.350(±0.000) &  0.000(±0.000) &  0.000(±0.000) &  0.000(±0.000) \\
       & 384 &  0.359(±0.012) &  0.009(±0.013) &  0.018(±0.030) &  0.011(±0.010) \\
       & 1792 &  0.402(±0.017) &  0.087(±0.023) &  0.077(±0.044) &  0.045(±0.037) \\
       & 3

## All classes mean and std

In [84]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [85]:
random_mean = np.array(df_img_random["All classes"]["mean"].values)
random_sd = np.array(df_img_random["All classes"]["std"].values)

In [86]:
bald_mean = np.array(df_img_bald["All classes"]["mean"].values)
bald_sd = np.array(df_img_bald["All classes"]["std"].values)

In [87]:
entropy_mean = np.array(df_img_entropy["All classes"]["mean"].values)
entropy_sd = np.array(df_img_entropy["All classes"]["std"].values)

In [88]:
ralis_mean = np.array(df_img_ralis["All classes"]["mean"].values)
ralis_sd = np.array(df_img_ralis["All classes"]["std"].values)

In [89]:
random_mean

array([0.367, 0.357, 0.377, 0.395, 0.464, 0.490])

In [90]:
random_sd

array([0.021, 0.009, 0.018, 0.036, 0.060, 0.045])

In [91]:
entropy_mean

array([0.350, 0.359, 0.402, 0.467, 0.503, 0.530])

In [92]:
entropy_sd

array([0.000, 0.012, 0.017, 0.053, 0.018, 0.009])

In [93]:
bald_mean

array([0.350, 0.373, 0.409, 0.364, 0.439, 0.536])

In [94]:
bald_sd

array([0.000, 0.023, 0.044, 0.162, 0.161, 0.028])

In [95]:
ralis_mean

array([0.351, 0.404, 0.480, 0.479, 0.519, 0.553])

In [96]:
ralis_sd

array([0.001, 0.030, 0.050, 0.015, 0.027, 0.016])